DATA_FILE_NAME = "data_baby.csv"
DATA_RESULT_FILE_NAME = "data_result.csv"

DATA_COLUMNS_CHR_TYPE = ["Sexe"]
DATA_COLUMN_TO_FIND = "PoidsBB"

DATA_MAX_LEARNING_ROW = 350

SIGMOID = 0
HYPERBOLIC_TANGENT = 1
PERCEPTRON_ACTIVATION_FUNCTION = SIGMOID